proxies:
  - {name: 🇺🇸 美国 V2CROSS.COM 1, server: 172.99.188.99, port: 2375, type: ss, cipher: aes-256-gcm, password: faBAoD54k87UJG7, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 2, server: 172.99.188.99, port: 5003, type: ss, cipher: aes-256-gcm, password: g5MeD6Ft3CWlJId, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 3, server: 172.99.188.99, port: 8882, type: ss, cipher: aes-256-gcm, password: kDWvXYZoTBcGkC4, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 4, server: 172.99.188.99, port: 5004, type: ss, cipher: aes-256-gcm, password: g5MeD6Ft3CWlJId, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 5, server: 172.99.188.99, port: 2375, type: ss, cipher: aes-256-gcm, password: faBAoD54k87UJG7, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 6, server: 172.99.188.99, port: 8882, type: ss, cipher: aes-256-gcm, password: kDWvXYZoTBcGkC4, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 7, server: 172.99.188.99, port: 5003, type: ss, cipher: aes-256-gcm, password: g5MeD6Ft3CWlJId, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 1, server: 173.245.59.168, port: 8080, type: vmess, uuid: 27848739-7e62-4138-9fd3-938a63964b6b, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /KTR, headers: {Host: 2.arvanktbr.store}}, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 8, server: zfc.windowsupdate1.com, port: 443, type: vmess, uuid: 3855b736-bf24-461f-b5b9-1d3f04484b37, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: "/yfjc/nl2?ed=2048", headers: {Host: nl2.yfjc.sbs}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 2, server: lv1.sharecentrepro.org, port: 443, type: vmess, uuid: 823c31da-701f-483d-b36e-896e5cf0987a, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, servername: lv1.sharecentrepro.org, network: ws, ws-opts: {path: /shirker, headers: {Host: lv1.sharecentrepro.org}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 3, server: usdo.tzccifq.ga, port: 443, type: vmess, uuid: 58eb724d-5a95-4b9c-851e-2cb3b408e85f, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: usdo.tzccifq.ga}}, udp: true}
  - {name: 🇺🇸 美国 RF Engineering, server: 141.193.213.21, port: 443, type: vmess, uuid: 2b214122-1906-428a-bbb7-a039cbb7cd5c, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /9JZFDTKE, headers: {Host: fr1.trump2023.org}}, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 9, server: 4559186168.xhtk.cc, port: 443, type: vmess, uuid: e1da11a9-6ab7-e0c3-3ca0-92ad364db204, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /lklcvws, headers: {Host: 4559186168.xhtk.cc}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare公司CDN节点(shopify) 1, server: 23.227.38.11, port: 443, type: vmess, uuid: 9379fea0-006d-4fd3-8e35-d45a5af72aa2, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /UMW36262, headers: {Host: frgt1.ssr-free2.xyz}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 4, server: germany1.yj2022.ga, port: 443, type: vmess, uuid: 4b5e4565-322f-4223-a891-78a84f189726, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /XQ2WCa29jfDMGBcbnQ, headers: {Host: germany1.yj2022.ga}}, udp: true}
  - {name: 🇺🇸 美国加利福尼亚州圣何塞 Cloudflare节点, server: 103.21.244.173, port: 80, type: vmess, uuid: f7738290-ba04-4dd1-b4f3-e6863a9e1c8a, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: zzsg.nmsl.pics}}, udp: true}
  - {name: 🇦🇺 澳大利亚 Cranbourne Secondary College, server: 203.30.191.6, port: 443, type: vmess, uuid: c5a2d7b8-bf84-4f97-8577-b9b87f2baaf7, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /AUIKN8AU, headers: {Host: oplg1.cfcdn2.xyz}}, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 10, server: vde2.0bad.com, port: 443, type: vmess, uuid: 927094d3-d678-4763-8591-e240d0bcae87, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /chat, headers: {Host: vde2.0bad.com}}, udp: true}
  - {name: 🇭🇰 香港 Amazon数据中心, server: hk80-2.af49c4e4c2ef.sanfen001.pics, port: 80, type: vmess, uuid: dcea7f3e-98ba-4ac8-a294-5092dc381a57, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: www.baidu.com}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 5, server: 172.64.154.103, port: 443, type: vmess, uuid: 5f64fa65-7b14-49c5-954d-aa15c6bfcacd, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: clash6.ssr-free.xyz}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 6, server: cf-lt.sharecentre.online, port: 443, type: vmess, uuid: a4921a75-0991-4d81-9721-8e45d2e31905, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, servername: dd3.1808.cf, network: ws, ws-opts: {path: /, headers: {Host: dd3.1808.cf}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 7, server: zhuyong.hucloud-dns.xyz, port: 443, type: vmess, uuid: 9a18cbb1-81d2-4720-9f09-46ea276b6ddb, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /huhublog, headers: {Host: zhuyong.hucloud-dns.xyz}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 8, server: ap.utopub.com, port: 443, type: vmess, uuid: a07030f3-a9e8-4e46-8d94-604fd70a8816, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: ap.utopub.com}}, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 11, server: zfc.windowsupdate1.com, port: 443, type: vmess, uuid: 27509613-bbd5-403a-868c-8022d36aa565, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: "/pq/fr1?ed=2048", headers: {Host: fr1.pqjc.buzz}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 9, server: sv3.adsensor.top, port: 80, type: vmess, uuid: 7a5af201-b588-4f13-9f02-185c68acd89b, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /manageit, headers: {Host: sv3.adsensor.top}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare公司CDN节点(shopify) 2, server: 23.227.38.11, port: 443, type: vmess, uuid: 9379fea0-006d-4fd3-8e35-d45a5af72aa2, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /UMW36262, headers: {Host: frgt1.ssr-free2.xyz}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 10, server: 172.67.46.53, port: 443, type: vmess, uuid: 5ce9cb0d-6b12-4dbd-9114-74fd11dc6f35, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: fr.binghe.design}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 11, server: hucloud.tk, port: 443, type: vmess, uuid: 2df3ed4a-4313-45f9-b742-2f02ce593a6e, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /huhu, headers: {Host: hucloud.tk}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 12, server: vc-usa.181227.xyz, port: 443, type: vmess, uuid: 6a091996-d012-4e5e-8448-8abe681eab99, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /vcus, headers: {Host: vc-usa.181227.xyz}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 13, server: de3.noml.app, port: 8080, type: vmess, uuid: 1a009014-28f7-4b34-97ce-afdf569975f1, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: de3.noml.app}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 14, server: 172.67.169.131, port: 443, type: vmess, uuid: c5a2d7b8-bf84-4f97-8577-b9b87f2baaf7, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: oplg1.cfcdn2.xyz}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 15, server: lv1.sharecentrepro.org, port: 443, type: vmess, uuid: 823c31da-701f-483d-b36e-896e5cf0987a, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, servername: lv1.sharecentrepro.org, network: ws, ws-opts: {path: /shirker, headers: {Host: lv1.sharecentrepro.org}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 16, server: america1.yj2022.ga, port: 443, type: vmess, uuid: 4b5e4565-322f-4223-a891-78a84f189726, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /vAambj4DgXrs5sfCFptMk, headers: {Host: america1.yj2022.ga}}, udp: true}
  - {name: 🇺🇸 美国 CloudFlare节点 17, server: cf-lt.sharecentre.online, port: 8880, type: vmess, uuid: e59bd762-dacd-445c-8e2a-e1c5812949cb, alterId: 0, cipher: auto, tls: false, skip-cert-verify: true, network: ws, ws-opts: {path: /, headers: {Host: ssrsub.v10.asuka.buzz}}, udp: true}
  - {name: 🇺🇸 美国 V2CROSS.COM 12, server: vus3.0bad.com, port: 443, type: vmess, uuid: 927094d3-d678-4763-8591-e240d0bcae87, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, network: ws, ws-opts: {path: /chat, headers: {Host: vus3.0bad.com}}, udp: true}
  - {name: 🇨🇳 广东省广州市 移动, server: hnm.xiaohouzi.club, port: 18831, type: trojan, password: 21e10785-99c6-316e-a184-a03384ee06e5, sni: hnm.xiaohouzi.club, skip-cert-verify: true, udp: true}

nodeList: &NodeList
  - 🇺🇸 美国 V2CROSS.COM 1
  - 🇺🇸 美国 V2CROSS.COM 2
  - 🇺🇸 美国 V2CROSS.COM 3
  - 🇺🇸 美国 V2CROSS.COM 4
  - 🇺🇸 美国 V2CROSS.COM 5
  - 🇺🇸 美国 V2CROSS.COM 6
  - 🇺🇸 美国 V2CROSS.COM 7
  - 🇺🇸 美国 V2CROSS.COM 8
  - 🇺🇸 美国 V2CROSS.COM 9
  - 🇺🇸 美国 V2CROSS.COM 10
  - 🇺🇸 美国 V2CROSS.COM 11
  - 🇺🇸 美国 V2CROSS.COM 12
  - 🇺🇸 美国 CloudFlare节点 1
  - 🇺🇸 美国 CloudFlare节点 2
  - 🇺🇸 美国 CloudFlare节点 3
  - 🇺🇸 美国 CloudFlare节点 4
  - 🇺🇸 美国 CloudFlare节点 5
  - 🇺🇸 美国 CloudFlare节点 6
  - 🇺🇸 美国 CloudFlare节点 7
  - 🇺🇸 美国 CloudFlare节点 9 
  - 🇺🇸 美国 CloudFlare节点 10
  - 🇺🇸 美国 CloudFlare节点 11
  - 🇺🇸 美国 CloudFlare节点 12
  - 🇺🇸 美国 CloudFlare节点 13
  - 🇺🇸 美国 CloudFlare节点 14
  - 🇺🇸 美国 CloudFlare节点 15
  - 🇺🇸 美国 CloudFlare节点 16
  - 🇺🇸 美国 CloudFlare节点 17
  - 🇺🇸 美国 CloudFlare节点 8
  - 🇺🇸 美国 CloudFlare公司CDN节点(shopify) 1
  - 🇺🇸 美国 CloudFlare公司CDN节点(shopify) 2
  - 🇺🇸 美国 RF Engineering
  - 🇺🇸 美国加利福尼亚州圣何塞 Cloudflare节点
  - 🇦🇺 澳大利亚 Cranbourne Secondary College
  - 🇭🇰 香港 Amazon数据中心
  - 🇨🇳 广东省广州市 移动

proxy-groups:
  - name: 🔰节点选择
    type: select
    proxies: *NodeList
  - name: ♻️自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies: *NodeList
